# ESLint version: 4.0.0
# Last updated: 2017-06-14

root: true
parserOptions:
    ecmaVersion: 8
env:
    node: true
    es6: true
rules:
    # Possible errors
    for-direction: warn
    no-await-in-loop: warn
    no-compare-neg-zero: error
    no-cond-assign: error
    no-constant-condition:
        - warn
        - checkLoops: false
    no-control-regex: error
    no-debugger: error
    no-dupe-args: error
    no-dupe-keys: error
    no-duplicate-case: error
    no-empty-character-class: warn
    no-empty:
        - warn
        - allowEmptyCatch: true
    no-ex-assign: error
    no-extra-boolean-cast: error
    no-extra-parens:
        - warn
        - all
        - conditionalAssign: false
          returnAssign: false
          nestedBinaryExpressions: false
    no-extra-semi: error
    no-func-assign: error
    no-inner-declarations:
        - error
        - both
    no-invalid-regexp: error
    no-irregular-whitespace:
        - error
        - skipStrings: false
    no-obj-calls: error
    no-prototype-builtins: warn
    no-regex-spaces: warn
    no-sparse-arrays: error
    no-template-curly-in-string: warn
    no-unexpected-multiline: error
    no-unreachable: error
    no-unsafe-finally: error
    no-unsafe-negation: error
    use-isnan: error
    # TODO
    valid-jsdoc: warn
    valid-typeof:
        - error
        - requireStringLiterals: true

    # Best practices
    accessor-pairs: warn
    array-callback-return: error
    class-methods-use-this: warn
    curly: error
    default-case:
        - warn
        - commentPattern: /^No default\.$/
    dot-location:
        - warn
        - property
    dot-notation: warn
    eqeqeq: warn
    guard-for-in: warn
    no-alert: error
    no-caller: error
    no-case-declarations: warn
    no-empty-function: warn
    no-empty-pattern: warn
    no-eval: error
    no-extend-native: error
    no-extra-bind: warn
    no-fallthrough:
        - warn
        - commentPattern: /^No break\.$/
    no-floating-decimal: error
    no-global-assign: error
    no-implicit-coercion: error
    no-implied-eval: error
    no-invalid-this: error
    no-iterator: error
    no-labels: error
    no-lone-blocks: warn
    no-loop-func: error
    no-multi-spaces: error
    no-multi-str: error
    no-new-func: error
    no-new-wrappers: error
    no-new: warn
    no-octal-escape: warn
    no-octal: warn
    no-param-reassign:
        - warn
        - props: false
    no-proto: error
    no-redeclare: error
    no-return-assign:
        - error
        - always
    no-return-await: error
    no-script-url: error
    no-self-assign:
        - error
        - props: true
    no-self-compare: warn
    no-sequences: error
    no-throw-literal: error
    no-unmodified-loop-condition: warn
    no-unused-expressions:
        - warn
        - allowShortCircuit: false
          allowTernary: false
    no-useless-call: warn
    no-useless-concat: warn
    no-useless-escape: warn
    no-useless-return: warn
    no-void: error
    no-warning-comments:
        - warn
        - terms:
            - todo
            - fixme
            - warn
            - warning
    no-with: warn
    radix:
        - warn
        - as-needed
    require-await: warn
    wrap-iife:
        - warn
        - any
    yoda:
        - warn
        - never
        - exceptRange: true

    # Strict mode
    strict:
        - error
        - global

    # Variables
    init-declarations:
        - warn
        - always
    no-delete-var: error
    no-shadow-restricted-names: error
    no-shadow:
        - warn
        - builtinGlobals: true
          allow:
              - err
              - model
              - Promise
              - response
              - result
    no-undef-init: error
    no-undef:
        - error
        - typeof: true
    no-undefined: error
    no-unused-vars:
        - warn
        - vars: all
          args: after-used
          caughtErrors: all
    no-use-before-define:
        - error
        - functions: false
          classes: true

    # Node.js and CommonJS
    callback-return:
        - warn
        - - next
          - resolve
          - reject
          - callback
    global-require: error
    handle-callback-err: warn
    no-buffer-constructor: error
    no-mixed-requires: error
    no-new-require: error
    no-path-concat: error

    # Stylistic issues
    array-bracket-spacing: warn
    block-spacing: warn
    brace-style: error
    camelcase:
        - warn
        - properties: never
    capitalized-comments:
        - warn
        - always
        - ignoreConsecutiveComments: true
    comma-dangle:
        - error
        - always-multiline
    comma-spacing: error
    comma-style: error
    computed-property-spacing: error
    consistent-this:
        - warn
        - vm
        - that
        - self
    eol-last: error
    func-call-spacing: error
    func-names:
        - error
        - never
    indent:
        - error
        - tab
        - SwitchCase: 1
    jsx-quotes: error
    key-spacing:
        - error
        - mode: minimum
    keyword-spacing: error
    linebreak-style: error
    lines-around-comment: error
    lines-around-directive: error
    max-depth: warn
    max-len:
        - warn
        - code: 100
    max-nested-callbacks:
        - error
        - max: 4
    max-statements-per-line: error
    new-cap: error
    new-parens: error
    no-array-constructor: error
    no-bitwise: warn
    no-lonely-if: warn
    no-mixed-operators: warn
    no-mixed-spaces-and-tabs:
        - error
        - smart-tabs
    no-multi-assign: error
    no-multiple-empty-lines:
        - error
        - max: 1
    no-nested-ternary: error
    no-new-object: error
    no-trailing-spaces: error
    no-underscore-dangle: error
    no-unneeded-ternary: warn
    no-whitespace-before-property: error
    object-curly-newline:
        - error
        - consistent: true
    object-curly-spacing:
        - error
        - always
    object-property-newline: error
    one-var:
        - error
        - never
    operator-assignment: warn
    operator-linebreak: warn
    padded-blocks:
        - error
        - never
    quote-props:
        - error
        - as-needed
    quotes:
        - error
        - double
        - avoidEscape: true
    semi-spacing: error
    semi-style: error
    semi: error
    space-before-blocks: error
    space-before-function-paren:
        - error
        - anonymous: never
          named: never
          asyncArrow: always
    space-in-parens: error
    space-infix-ops: error
    space-unary-ops: error
    spaced-comment: error
    switch-colon-spacing: error
    template-tag-spacing: error
    unicode-bom: error

    # ECMAScript 6
    arrow-parens: warn
    arrow-spacing: error
    constructor-super: error
    generator-star-spacing:
        - warn
        - after
    no-class-assign: error
    no-confusing-arrow:
        - warn
        - allowParens: true
    no-const-assign: error
    no-dupe-class-members: error
    no-duplicate-imports: warn
    no-new-symbol: error
    no-this-before-super: error
    no-useless-computed-key: warn
    no-useless-constructor: warn
    no-useless-rename: warn
    no-var: error
    prefer-arrow-callback: warn
    prefer-rest-params: error
    prefer-spread: warn
    require-yield: error
    rest-spread-spacing: error
    symbol-description: warn
    template-curly-spacing: error
    yield-star-spacing: warn
