export const LOAD_DEVICES = "LOAD_DEVICES";
export const SET_ACTIVE_DEVICE = "SET_ACTIVE_DEVICE";

export const INIT_SOCKET = "INIT_SOCKET";
export const LOAD_TAGS = "LOAD_TAGS";
export const TOGGLE_MONITOR = "TOGGLE_MONITOR";
export const UPDATE_TAG = "UPDATE_TAG";
export const LOAD_TAG_HISTORY = "LOAD_TAG_HISTORY";
export const SELECT_TAG = "SELECT_TAG";

export const LOAD_GROUPS = "LOAD_GROUPS";
export const CREATE_GROUP = "CREATE_GROUP";
export const ADD_TAG_TO_GROUP = "ADD_TAG_TO_GROUP";
export const REMOVE_TAG_FROM_GROUP = "REMOVE_TAG_FROM_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";

export const LOAD_NODES = "LOAD_NODES";
export const UPDATE_BREADCRUMB = "UPDATE_BREADCRUMB";

export const LOAD_SCREENS = "LOAD_SCREENS";
export const SET_ACTIVE_COMPONENT = "SET_ACTIVE_COMPONENT";
export const SAVE_COMPONENT = "SAVE_COMPONENT";
export const DELETE_COMPONENT = "DELETE_COMPONENT";
