export const LOAD_DEVICES = "LOAD_DEVICES";
export const SET_SELECTED_DEVICE = "SET_SELECTED_DEVICE";

export const INIT_SOCKET = "INIT_SOCKET";
export const LOAD_TAGS = "LOAD_TAGS";
export const TOGGLE_MONITOR = "TOGGLE_MONITOR";
export const UPDATE_TAG = "UPDATE_TAG";

export const LOAD_NODES = "LOAD_NODES";
export const UPDATE_BREADCRUMB = "UPDATE_BREADCRUMB";

export const LOAD_SCREENS = "LOAD_SCREENS";
